config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'tweets/new' => 'tweets#new'
  get 'tweets/test'=>'tweets#test'
  root 'hello#index'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user, dependent: :destroy
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet, dependent: :destroy


  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end

    def link
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
 end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!

    def index
      if params[:question1] == nil
        @tweets= Tweet.all
      elsif params[:question1] == ''
        @tweets= Tweet.all
      else
        @tweets = Tweet.where(body: params[:question1], season: params[:question2], feel: params[:question3])
      end
    end

    def new
        @tweet = Tweet.new
      end

      def create
        tweet = Tweet.new(tweet_params)

        tweet.user_id = current_user.id

        if tweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @tweet = Tweet.find(params[:id])
      end

      def edit
        @tweet = Tweet.find(params[:id])
      end

      def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
      end

      def test
      end
    
      private
      def tweet_params
        params.require(:tweet).permit(:body,:season,:feel,:image)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hello/index.html.erb
  
  <div class="slider">
  <div class="slider-inner">
      <div class="slider-item"><%= image_tag 'futari.png' %></div>
      <div class="slider-item"><%= image_tag 'huku.png' %></div>
      <div class="slider-item"><%= image_tag 'inu.png' %></div>
  </div>
</div>

   
   

app/views/hello/link.html.erb
My name is GeekSalon.
<%= link_to 'トップページ', hello_index_path %>
<%= link_to '一覧表示', :controller => "tweets", :action => "index" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/09c41affa1.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <header>
    <h1>My stylist</h1>

   
   
    <div class="header-list">
   <ul>
  <div class="gnavi">
      <li><%= link_to "log in", tweets_path %><span class="linkhover">ログイン<span></li></li>
      <li><%= link_to "home", root_path %><span class="linkhover">ホーム<span></li>
      <li><%= link_to "post", tweets_path %><span class="linkhover">投稿一覧<span></li>
      <li><%= link_to "new post",tweets_new_path %><span class="linkhover">新規投稿<span</li>
      <li><%= link_to "test",tweets_test_path %><span class="linkhover">診断<span</li>
      </ul>
    </ul>
    </div>
    </div>
    <link rel="stylesheet" type="text/css" href="css/5-3-9.css">
    </header>
  <main>
    <%= yield %>
   
   
  
</main>
  <footer>
      <ul>
      <li><%= link_to "sign up", new_user_registration_path %></li>
      <li><%= button_to "log out", destroy_user_session_path, method: :delete %></li>
      <li><p>Copyright © GeekSalon All Rights Reserved.</p></li>
      </ul>


    </footer>
  

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
    <script
    src="https://code.jquery.com/jquery-3.6.3.min.js"
    integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
    crossorigin="anonymous"></script>

    </body>
</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/index.html.erb
<h3>投稿一覧</h3>



<div class="container">
			    <div class="row">
                <% @tweets.each do |t| %>  
                <div class="col-md-3">    
                        <div class="card" style="width: 15rem;">
                  
                 <div class="cardura">
                   <div class="card-body">
                  
                  <%= image_tag t.image_url, size: "250x200" if t.image? %>
                  
                    <%= t.body %>
                    <%= t.season %>
                    <%= t.feel %>

                   </div>


                    <p class="card-text"></p>
			                
			                <% if user_signed_in? %>
                          <% if current_user.already_liked?(t) %>
                           <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                           <i class="fas fa-heart"></i><%= t.likes.count %>
                           <% end %>
                        <% else %>
                            <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                            <i class="far fa-heart"></i><%= t.likes.count %>
                            <% end %>
                        <% end %>
                     <% else %>
                        <i class="far fa-heart"></i><%= t.likes.count %>
                     <% end %>

      
      <%= link_to "詳細へ", tweet_path(t.id) %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete %>
      
                 </div>
			            </div>
                </div>
			        <% end %>
			    </div>
</div>

app/views/tweets/new.html.erb
<h3>新規投稿</h3>

<div class="container">
			    <div class="row">
          <%= form_for @tweet do |f| %>
                <div class="col-md-4">    
                        <div class="card" style="width: 32rem;">
   <div class="cardura">
    <div class="field">
    <%= f.label :body %>
    <%= f.radio_button :body, "晴" %>晴
    <%= f.radio_button :body, "雨" %>雨
    <%= f.radio_button :body, "曇" %>曇
    <br>

    <%= f.label :season %>
    <%= f.radio_button :season, "春" %>春
    <%= f.radio_button :season, "夏" %>夏
    <%= f.radio_button :season, "秋" %>秋
    <%= f.radio_button :season, "冬" %>冬
    <br>

    <%= f.label :feel %>
    <%= f.radio_button :feel, "モノトーン" %>モノトーン
    <%= f.radio_button :feel, "ビビット" %>ビビット
    <%= f.radio_button :feel, "パステル" %>パステル
    
    <br>

    
    <%= f.label :image %>
    <%= f.file_field :image %>
    
   
  </div>
  
  <div class="submit">
  <%= f.submit "投稿する" %>
  <rb>
  <%= link_to "投稿一覧に戻る", tweets_path %>

<% end %>
    </div>
    </div>

</div>
</div>
</div>
<br>
<div class="back"><%= image_tag 'monoto.png' %></div>

</div>


<%= stylesheet_link_tag 'new', :media => "all" %>

app/views/tweets/show.html.erb
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(@tweet), method: :delete do %>
            <i class="fas fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
      <% else %>
        <%= link_to tweet_likes_path(@tweet), method: :post do %>
            <i class="far fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @tweet.likes.count %>
    <% end %>
  


<h4>いいねしたユーザー</h4>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>


<div class="line">
<%= link_to "Tweet一覧に戻る", tweets_path %>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

</div>
</div>

app/views/tweets/test.html.erb
<h2>診断<h2>

  <div class="test">
     <div class="row">
        <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
          <div class="col-md-4">    
              <div class="card" style="width: 25rem;">
              
    <div class="cardura">
    <div class="tenki">
    <p>Question1. 天気</p>
    <%= radio_button_tag :question1, '晴',class: "i" %>晴
    <%= radio_button_tag :question1, '曇',class: "i" %>曇
    <%= radio_button_tag :question1, '雨',class: "i" %>雨
    

    <p>Question2. 季節</p>
    <%= radio_button_tag :question2, '春',class: "i" %>春
    <%= radio_button_tag :question2, '夏',class: "i" %>夏
    <%= radio_button_tag :question2, '秋',class: "i" %>秋
    <%= radio_button_tag :question2, '冬',class: "i" %>冬
    
    <p>Question3. 色</p>
    <%= radio_button_tag :question3, 'モノトーン',class: "i" %>モノトーン
    <%= radio_button_tag :question3, 'ビビット',class: "i" %>ビビット
    <%= radio_button_tag :question3, 'パステル',class: "i" %>パステル


    <div class="submit">
    <%= submit_tag "診断する" %>
    </div>
<% end %>
</div>
</div>
</div>
</div>
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>